name = "telegram-trip-journal-bot"
main = "worker.js"
compatibility_date = "2024-09-22"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.production.vars]
TELEGRAM_BOT_TOKEN = ""
GOOGLE_SHEET_ID = ""
ADMIN_IDS = ""
GOOGLE_SHEET_NAME = "Лист1"
TIMEZONE = "Europe/Moscow"

[[env.production.kv_namespaces]]
binding = "USERS_KV"
id = ""

[triggers]
crons = ["0 */6 * * *"]
